const { sendMessage } = require('../handles/sendMessage');

module.exports = {
  name: ['resume', 'cv', 'create resume', 'make resume', 'gawa resume', 'gumawa ng resume', 'resume for', 'make a resume', 'create a resume'],
  description: 'Generate resume templates',
  usage: 'resume [job]',
  version: '2.0.0',
  author: 'codex',
  category: 'Utility',
  cooldown: 5,

  async execute(senderId, args, token, event) {
    try {
      const prompt = args.join(' ').trim().toLowerCase();
      
      if (!prompt) {
        const jobs = 'cashier, medic, janitor, supervisor, laborer, security, teacher, driver, sales, nurse, cook, engineer, accountant, waiter, barista, caregiver, receptionist, technician';
        await sendMessage(senderId, { text: 'RESUME GENERATOR\n\nAvailable Jobs:\n' + jobs + '\n\nUsage:\nresume [job]\nmake a resume for [job]\ncreate resume for [job]\ngawa ng resume para sa [job]' }, token);
        return;
      }
      
      const jobType = this.detectJob(prompt);
      
      if (!jobType) {
        const jobs = 'cashier, medic, janitor, supervisor, laborer, security, teacher, driver, sales, nurse, cook, engineer, accountant, waiter, barista, caregiver, receptionist, technician';
        await sendMessage(senderId, { text: 'Job not found.\n\nAvailable Jobs:\n' + jobs }, token);
        return;
      }
      
      const resume = this.getResume(jobType);
      
      if (resume) {
        await sendMessage(senderId, { text: resume }, token);
      } else {
        await sendMessage(senderId, { text: 'No template found for this job.' }, token);
      }
      
    } catch (error) {
      console.error('[resume] Error:', error.message);
      await sendMessage(senderId, { text: 'Error: ' + error.message }, token);
    }
  },

  detectJob(prompt) {
    const jobs = [
      { key: 'cashier', keywords: ['cashier', 'kahera', 'kahero'] },
      { key: 'medic', keywords: ['medic', 'medical'] },
      { key: 'janitor', keywords: ['janitor', 'cleaner'] },
      { key: 'supervisor', keywords: ['supervisor', 'team leader', 'manager'] },
      { key: 'laborer', keywords: ['laborer', 'labourer', 'construction'] },
      { key: 'security', keywords: ['security', 'guard'] },
      { key: 'teacher', keywords: ['teacher', 'educator', 'tutor', 'guro'] },
      { key: 'driver', keywords: ['driver', 'drayber'] },
      { key: 'sales', keywords: ['sales'] },
      { key: 'nurse', keywords: ['nurse', 'nars'] },
      { key: 'cook', keywords: ['cook', 'chef', 'kusinero'] },
      { key: 'engineer', keywords: ['engineer', 'inhinyero'] },
      { key: 'accountant', keywords: ['accountant', 'bookkeeper', 'accounting'] },
      { key: 'waiter', keywords: ['waiter', 'server', 'weyter'] },
      { key: 'barista', keywords: ['barista', 'coffee', 'cafe'] },
      { key: 'caregiver', keywords: ['caregiver', 'nanny', 'yaya'] },
      { key: 'receptionist', keywords: ['receptionist', 'front desk'] },
      { key: 'technician', keywords: ['technician', 'teknisyan'] }
    ];
    
    for (const job of jobs) {
      if (job.keywords.some(k => prompt.includes(k))) return job.key;
    }
    return null;
  },

  getResume(jobType) {
    const L = '──────────────────────────────────────';
    const header = 'JUAN DELA CRUZ (example lang — palitan mo ng actual name)\nEmail: juandelacruz@gmail.com | Contact No.: 09123456789 | Address: Muntinlupa City, Philippines\n\n';
    
    const templates = {};
    
    // CASHIER
    templates.cashier = header + L + '\n\nPROFESSIONAL SUMMARY\n\nMotivated and results-driven professional with extensive experience in customer service, cash handling, and retail operations. Possesses strong communication, teamwork, and problem-solving skills, with a proven ability to thrive and maintain accuracy in fast-paced environments.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: February 28, 1998\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nCashier\nSM Hypermarket – SM Tunasan\n\n· Processed cash, credit, and digital payments accurately and efficiently.\n· Greeted customers warmly, answered inquiries, and assisted with purchases.\n· Conducted opening and closing cash counts daily.\n\nCashier\nSuperCity Alabang Landmark – Alabang, Muntinlupa\n\n· Processed cash, credit, and digital payments accurately and efficiently.\n· Greeted customers warmly, answered inquiries, and assisted with purchases.\n· Conducted opening and closing cash counts daily.\n\nService Crew (Cashier)\nJollibee Shell SLT Alabang\n\n· Took accurate food and beverage orders from customers efficiently.\n· Prepared food items according to established standard operating procedures.\n· Maintained cleanliness and organization in dining and kitchen areas.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Criminology\nPamantasan ng Lungsod ng Muntinlupa\n2018\n\nMuntinlupa National High School (MNHS)\n2010 – 2014\n\nMuntinlupa Elementary School (MES)\n2004 – 2010\n\n' + L + '\n\nSKILLS\n\n· Cash Handling & POS Operation\n· Teamwork & Collaboration\n· Sales & Promotions\n· Time Management & Adaptability\n· Effective Communication\n\n' + L + '\n\nREFERENCES\n\nAngelika Mae Lopez\nHR Assistant\n09911451130\n\nCzerina Mae Espenesin\nAccounting Assistant | Mabex Manufacturing Inc.\n09928196248\n\nMenchie Donayre\nGraphic Designer\n09563892622';

    // MEDIC
    templates.medic = header + L + '\n\nPROFESSIONAL SUMMARY\n\nCompassionate and dedicated healthcare professional with experience in patient care, emergency response, and medical assistance. Skilled in providing quality healthcare services, maintaining patient records, and assisting medical teams in fast-paced clinical environments.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: March 15, 1995\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English, Tagalog, and Bisaya\n\n' + L + '\n\nWORK EXPERIENCES\n\nEmergency Medical Technician (EMT)\nAmbulance Services – Muntinlupa City\n\n· Responded to emergency calls and provided immediate medical care.\n· Assessed patient conditions and administered basic life support.\n· Transported patients safely to medical facilities.\n\nMedical Assistant\nHealth Center – Barangay Tunasan\n\n· Assisted physicians with patient examinations and procedures.\n· Recorded patient vital signs and medical history accurately.\n· Maintained cleanliness and sterilization of medical equipment.\n\nFirst Aid Responder\nCompany Clinic – Alabang\n\n· Provided first aid treatment to employees for minor injuries.\n· Conducted health awareness programs and first aid training.\n· Maintained inventory of medical supplies.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Nursing\nPamantasan ng Lungsod ng Muntinlupa\n2017\n\nMuntinlupa National High School (MNHS)\n2009 – 2013\n\nMuntinlupa Elementary School (MES)\n2003 – 2009\n\n' + L + '\n\nSKILLS\n\n· Patient Care & Assessment\n· Basic Life Support (BLS)\n· First Aid & Emergency Response\n· Medical Record Keeping\n· Communication & Interpersonal Skills\n\n' + L + '\n\nREFERENCES\n\nDr. Maria Santos\nMedical Director\n09987654321\n\nDr. Jose Reyes\nER Physician\n09876543210\n\nNurse Ana Lopez\nHead Nurse\n09765432109';

    // JANITOR
    templates.janitor = header + L + '\n\nPROFESSIONAL SUMMARY\n\nHardworking and reliable janitorial professional with extensive experience in cleaning, sanitation, and facility maintenance. Dedicated to maintaining clean, safe, and organized environments.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: January 10, 1990\n· Religion: Roman Catholic\n· Civil Status: Married\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nJanitor / Cleaner\nSM Mall – Muntinlupa City\n\n· Performed daily cleaning and sanitation of mall common areas.\n· Operated floor cleaning machines and janitorial equipment.\n· Ensured proper waste segregation and disposal.\n\nBuilding Maintenance\nOffice Building – Alabang\n\n· Maintained cleanliness of office spaces and conference rooms.\n· Replenished cleaning supplies and restroom consumables.\n· Reported maintenance issues such as leaks and damages.\n\nUtility Worker\nSchool Campus – Tunasan\n\n· Cleaned classrooms, corridors, and school facilities daily.\n· Assisted in setting up venues for school events.\n· Followed safety protocols in handling cleaning chemicals.\n\n' + L + '\n\nEDUCATION\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2004 – 2008\n\nMuntinlupa Elementary School (MES)\n1998 – 2004\n\n' + L + '\n\nSKILLS\n\n· Floor Care & Maintenance\n· Cleaning Equipment Operation\n· Waste Management & Segregation\n· Time Management & Reliability\n· Health & Safety Compliance\n\n' + L + '\n\nREFERENCES\n\nMr. Roberto Gomez\nFacilities Manager\n09123456789\n\nMs. Linda Cruz\nAdmin Supervisor\n09234567890\n\nMr. Mario Diaz\nOperations Head\n09345678901';

    // SUPERVISOR
    templates.supervisor = header + L + '\n\nPROFESSIONAL SUMMARY\n\nResults-oriented supervisor with proven leadership experience in managing teams, improving operational efficiency, and ensuring quality standards.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: May 20, 1988\n· Religion: Roman Catholic\n· Civil Status: Married\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nOperations Supervisor\nRetail Store – Alabang\n\n· Supervised daily operations and managed a team of 15+ staff members.\n· Monitored employee performance and provided coaching and feedback.\n· Ensured compliance with company policies and customer service standards.\n\nTeam Leader\nBPO Company – Muntinlupa City\n\n· Led a team of 10 customer service representatives.\n· Conducted regular team meetings and performance reviews.\n· Achieved monthly targets through effective team management.\n\nShift Supervisor\nFast Food Chain – Tunasan\n\n· Managed shift schedules and assigned tasks to crew members.\n· Handled customer complaints and resolved issues promptly.\n· Ensured food safety and quality standards were consistently met.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Business Administration\nPamantasan ng Lungsod ng Muntinlupa\n2010\n\nMuntinlupa National High School (MNHS)\n2002 – 2006\n\nMuntinlupa Elementary School (MES)\n1996 – 2002\n\n' + L + '\n\nSKILLS\n\n· Team Leadership & Management\n· Performance Monitoring & Evaluation\n· Customer Service Excellence\n· Problem Solving & Decision Making\n· Time Management & Delegation\n\n' + L + '\n\nREFERENCES\n\nMs. Grace Martinez\nOperations Manager\n09123456789\n\nMr. David Garcia\nHR Manager\n09234567890\n\nMs. Rachel Tan\nSenior Manager\n09345678901';

    // LABORER
    templates.laborer = header + L + '\n\nPROFESSIONAL SUMMARY\n\nHardworking and physically fit laborer with experience in construction, warehouse operations, and general labor.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: July 15, 1992\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nConstruction Laborer\nConstruction Site – Muntinlupa City\n\n· Assisted in loading and unloading construction materials.\n· Operated hand tools and equipment under supervision.\n· Maintained cleanliness and order at the construction site.\n\nWarehouse Helper\nLogistics Company – Alabang\n\n· Assisted in receiving, sorting, and organizing warehouse inventory.\n· Loaded and unloaded goods from delivery trucks.\n· Followed safety guidelines in handling heavy materials.\n\nGeneral Laborer\nFactory – Tunasan\n\n· Performed general labor tasks as assigned by supervisor.\n· Maintained cleanliness of work area and equipment.\n· Assisted in production line operations when needed.\n\n' + L + '\n\nEDUCATION\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2006 – 2010\n\nMuntinlupa Elementary School (MES)\n2000 – 2006\n\n' + L + '\n\nSKILLS\n\n· Heavy Lifting & Material Handling\n· Hand Tool Operation\n· Safety Awareness\n· Teamwork & Cooperation\n· Physical Stamina & Endurance\n\n' + L + '\n\nREFERENCES\n\nMr. Ramon Reyes\nSite Engineer\n09123456789\n\nMr. Carlos Santos\nWarehouse Manager\n09234567890\n\nMr. Eduardo Lopez\nFactory Supervisor\n09345678901';

    // SECURITY
    templates.security = header + L + '\n\nPROFESSIONAL SUMMARY\n\nVigilant and dependable security professional with experience in safeguarding properties, monitoring surveillance systems, and ensuring the safety of personnel and visitors.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: September 5, 1990\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nSecurity Guard\nSM Mall – Muntinlupa City\n\n· Monitored CCTV cameras and conducted regular patrols of the premises.\n· Controlled access to restricted areas and verified identification.\n· Responded to emergencies and prepared incident reports.\n\nSecurity Officer\nOffice Building – Alabang\n\n· Greeted visitors and directed them to appropriate offices.\n· Maintained logbooks for visitors, vehicles, and deliveries.\n· Enforced building security policies and procedures.\n\nSecurity Guard\nResidential Subdivision – Tunasan\n\n· Patrolled residential areas to deter criminal activity.\n· Checked gates and perimeter fences regularly.\n· Assisted residents with security concerns and emergencies.\n\n' + L + '\n\nEDUCATION\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2004 – 2008\n\nMuntinlupa Elementary School (MES)\n1998 – 2004\n\n' + L + '\n\nSKILLS\n\n· CCTV Monitoring & Surveillance\n· Access Control & Visitor Management\n· Emergency Response & First Aid\n· Report Writing & Documentation\n· Physical Fitness & Alertness\n\n' + L + '\n\nREFERENCES\n\nMr. Antonio Reyes\nSecurity Agency Manager\n09123456789\n\nMs. Maria Garcia\nProperty Manager\n09234567890\n\nMr. Jose Martinez\nSecurity Supervisor\n09345678901';

    // TEACHER
    templates.teacher = header + L + '\n\nPROFESSIONAL SUMMARY\n\nPassionate and dedicated educator with experience in teaching, curriculum development, and student assessment.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: November 12, 1993\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English, Tagalog, and Bisaya\n\n' + L + '\n\nWORK EXPERIENCES\n\nTeacher I\nMuntinlupa National High School\n\n· Developed and implemented lesson plans aligned with curriculum standards.\n· Assessed student performance through quizzes, exams, and projects.\n· Maintained effective communication with parents.\n\nSubstitute Teacher\nMuntinlupa Elementary School\n\n· Taught various subjects including English, Math, and Science.\n· Managed classroom behavior and ensured a conducive learning environment.\n· Provided additional support to students with learning difficulties.\n\nTutor\nPrivate Tutorial Center – Alabang\n\n· Conducted one-on-one tutoring sessions for students.\n· Developed personalized learning materials based on student needs.\n· Tracked student improvement and adjusted teaching methods.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Secondary Education\nPamantasan ng Lungsod ng Muntinlupa\n2015\n\nMuntinlupa National High School (MNHS)\n2007 – 2011\n\nMuntinlupa Elementary School (MES)\n2001 – 2007\n\n' + L + '\n\nSKILLS\n\n· Lesson Planning & Delivery\n· Classroom Management\n· Student Assessment & Evaluation\n· Parent Communication\n· Educational Technology\n\n' + L + '\n\nREFERENCES\n\nDr. Maria Santos\nSchool Principal\n09123456789\n\nMs. Ana Reyes\nDepartment Head\n09234567890\n\nMr. Jose Garcia\nMaster Teacher\n09345678901';

    // DRIVER
    templates.driver = header + L + '\n\nPROFESSIONAL SUMMARY\n\nExperienced and safety-conscious driver with extensive knowledge of road safety regulations and vehicle maintenance.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: April 8, 1988\n· Religion: Roman Catholic\n· Civil Status: Married\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nCompany Driver\nLogistics Company – Muntinlupa City\n\n· Transported goods and materials to various destinations.\n· Maintained vehicle cleanliness and performed basic maintenance checks.\n· Kept accurate records of trips and deliveries.\n\nDelivery Driver\nFood Delivery Service – Alabang\n\n· Delivered food orders to customers in a timely manner.\n· Ensured customer satisfaction through professional service.\n· Managed cash and digital payments.\n\nShuttle Driver\nOffice Building – Tunasan\n\n· Transported employees to and from designated locations.\n· Followed scheduled routes and maintained punctuality.\n· Assisted passengers with luggage.\n\n' + L + '\n\nEDUCATION\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2002 – 2006\n\nMuntinlupa Elementary School (MES)\n1996 – 2002\n\n' + L + '\n\nSKILLS\n\n· Defensive Driving\n· Route Planning & Navigation\n· Vehicle Maintenance\n· Customer Service\n· Time Management\n\n' + L + '\n\nREFERENCES\n\nMr. Roberto Gomez\nOperations Manager\n09123456789\n\nMs. Linda Cruz\nHR Supervisor\n09234567890\n\nMr. Mario Diaz\nLogistics Head\n09345678901';

    // SALES
    templates.sales = header + L + '\n\nPROFESSIONAL SUMMARY\n\nDynamic and goal-oriented sales professional with proven track record in achieving sales targets and building strong customer relationships.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: June 25, 1995\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nSales Associate\nSM Department Store – Muntinlupa City\n\n· Assisted customers in finding products and making purchase decisions.\n· Achieved monthly sales targets through effective selling techniques.\n· Maintained product displays and ensured stock availability.\n\nSales Representative\nRetail Store – Alabang\n\n· Promoted products and services to potential customers.\n· Built and maintained relationships with regular clients.\n· Processed sales transactions and handled customer inquiries.\n\nSales Clerk\nBoutique – Tunasan\n\n· Provided personalized customer service to shoppers.\n· Managed inventory and restocked shelves regularly.\n· Handled cash register and credit card transactions.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Business Administration\nPamantasan ng Lungsod ng Muntinlupa\n2017\n\nMuntinlupa National High School (MNHS)\n2009 – 2013\n\nMuntinlupa Elementary School (MES)\n2003 – 2009\n\n' + L + '\n\nSKILLS\n\n· Sales & Negotiation\n· Customer Relationship Management\n· Product Knowledge\n· Communication & Persuasion\n· Goal Setting & Achievement\n\n' + L + '\n\nREFERENCES\n\nMs. Grace Martinez\nStore Manager\n09123456789\n\nMr. David Garcia\nSales Supervisor\n09234567890\n\nMs. Rachel Tan\nRegional Manager\n09345678901';

    // NURSE
    templates.nurse = header + L + '\n\nPROFESSIONAL SUMMARY\n\nCompassionate and skilled registered nurse with experience in patient care, medication administration, and health education.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: October 3, 1994\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English, Tagalog, and Bisaya\n\n' + L + '\n\nWORK EXPERIENCES\n\nStaff Nurse\nMuntinlupa City Hospital\n\n· Provided direct patient care including medication administration and vital signs monitoring.\n· Collaborated with physicians and healthcare team in developing care plans.\n· Educated patients and families on health management.\n\nClinic Nurse\nCompany Clinic – Alabang\n\n· Conducted health assessments and provided first aid treatment.\n· Maintained accurate patient records and documentation.\n· Administered vaccinations and conducted health screenings.\n\nPrivate Duty Nurse\nHome Care – Tunasan\n\n· Provided personalized nursing care to patients in home settings.\n· Monitored patient conditions and reported changes to physicians.\n· Assisted with activities of daily living and medication management.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Nursing\nPamantasan ng Lungsod ng Muntinlupa\n2016\n\nMuntinlupa National High School (MNHS)\n2008 – 2012\n\nMuntinlupa Elementary School (MES)\n2002 – 2008\n\n' + L + '\n\nSKILLS\n\n· Patient Care & Assessment\n· Medication Administration\n· IV Therapy & Wound Care\n· Health Education & Counseling\n· Critical Thinking & Decision Making\n\n' + L + '\n\nREFERENCES\n\nDr. Maria Santos\nChief Nurse\n09123456789\n\nDr. Jose Reyes\nMedical Director\n09234567890\n\nNurse Ana Lopez\nNurse Supervisor\n09345678901';

    // COOK
    templates.cook = header + L + '\n\nPROFESSIONAL SUMMARY\n\nSkilled and creative cook with experience in food preparation, kitchen management, and menu planning.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: August 18, 1991\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nCook\nRestaurant – Alabang\n\n· Prepared and cooked menu items according to recipes and standards.\n· Maintained cleanliness and organization of kitchen workstations.\n· Assisted in menu planning and food cost management.\n\nLine Cook\nFast Food Chain – Muntinlupa City\n\n· Prepared food items quickly and accurately during peak hours.\n· Followed food safety and sanitation guidelines strictly.\n· Collaborated with kitchen team to ensure efficient service.\n\nKitchen Helper\nHotel – Tunasan\n\n· Assisted chefs in food preparation and plating.\n· Maintained inventory of kitchen supplies and ingredients.\n· Cleaned and sanitized kitchen equipment and utensils.\n\n' + L + '\n\nEDUCATION\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2005 – 2009\n\nMuntinlupa Elementary School (MES)\n1999 – 2005\n\n' + L + '\n\nSKILLS\n\n· Food Preparation & Cooking\n· Kitchen Sanitation & Safety\n· Menu Planning\n· Time Management\n· Teamwork & Communication\n\n' + L + '\n\nREFERENCES\n\nChef Roberto Gomez\nExecutive Chef\n09123456789\n\nMs. Linda Cruz\nRestaurant Manager\n09234567890\n\nMr. Mario Diaz\nKitchen Supervisor\n09345678901';

    // ENGINEER
    templates.engineer = header + L + '\n\nPROFESSIONAL SUMMARY\n\nHighly skilled and detail-oriented engineer with experience in project management, design, and quality assurance.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: December 12, 1990\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nSite Engineer\nConstruction Company – Muntinlupa City\n\n· Supervised construction activities and ensured compliance with specifications.\n· Coordinated with contractors and suppliers for project requirements.\n· Prepared progress reports and maintained project documentation.\n\nProject Engineer\nEngineering Firm – Alabang\n\n· Assisted in project planning, design, and implementation.\n· Conducted site inspections and quality control checks.\n· Prepared technical drawings and specifications.\n\nCAD Engineer\nDesign Office – Tunasan\n\n· Created detailed engineering drawings using CAD software.\n· Reviewed and revised designs based on client feedback.\n· Collaborated with design team to meet project deadlines.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Civil Engineering\nPamantasan ng Lungsod ng Muntinlupa\n2012\n\nMuntinlupa National High School (MNHS)\n2004 – 2008\n\nMuntinlupa Elementary School (MES)\n1998 – 2004\n\n' + L + '\n\nSKILLS\n\n· Project Management\n· AutoCAD & Engineering Software\n· Quality Assurance & Control\n· Technical Drawing & Design\n· Problem Solving & Analysis\n\n' + L + '\n\nREFERENCES\n\nEngr. Ramon Reyes\nProject Manager\n09123456789\n\nEngr. Carlos Santos\nEngineering Head\n09234567890\n\nEngr. Eduardo Lopez\nSenior Engineer\n09345678901';

    // ACCOUNTANT
    templates.accountant = header + L + '\n\nPROFESSIONAL SUMMARY\n\nDetail-oriented and analytical accountant with experience in financial reporting, bookkeeping, and tax preparation.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: February 14, 1993\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nAccountant\nAccounting Firm – Muntinlupa City\n\n· Prepared financial statements and reports for clients.\n· Managed accounts payable and receivable.\n· Conducted bank reconciliations and general ledger maintenance.\n\nBookkeeper\nRetail Company – Alabang\n\n· Recorded daily financial transactions accurately.\n· Prepared monthly financial summaries and reports.\n· Assisted in payroll processing and tax filing.\n\nAccounting Assistant\nManufacturing Company – Tunasan\n\n· Assisted in preparing budgets and financial forecasts.\n· Processed invoices and expense reports.\n· Maintained organized financial records and documentation.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Accountancy\nPamantasan ng Lungsod ng Muntinlupa\n2015\n\nMuntinlupa National High School (MNHS)\n2007 – 2011\n\nMuntinlupa Elementary School (MES)\n2001 – 2007\n\n' + L + '\n\nSKILLS\n\n· Financial Reporting & Analysis\n· Bookkeeping & General Ledger\n· Tax Preparation & Compliance\n· Accounting Software Proficiency\n· Attention to Detail & Accuracy\n\n' + L + '\n\nREFERENCES\n\nMs. Grace Martinez\nAccounting Manager\n09123456789\n\nMr. David Garcia\nFinance Director\n09234567890\n\nMs. Rachel Tan\nSenior Accountant\n09345678901';

    // WAITER
    templates.waiter = header + L + '\n\nPROFESSIONAL SUMMARY\n\nFriendly and efficient waiter with experience in food service, customer relations, and order management.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: July 20, 1996\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nWaiter\nRestaurant – Alabang\n\n· Greeted customers and presented menus with recommendations.\n· Took accurate food and beverage orders.\n· Served food and drinks promptly and professionally.\n\nServer\nCafe – Muntinlupa City\n\n· Prepared and served coffee and food items to customers.\n· Maintained cleanliness of dining area and service stations.\n· Processed payments using POS system.\n\nFood Server\nHotel Restaurant – Tunasan\n\n· Provided quality dining service to hotel guests.\n· Set up dining tables and maintained table cleanliness.\n· Assisted in banquet and event services.\n\n' + L + '\n\nEDUCATION\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2010 – 2014\n\nMuntinlupa Elementary School (MES)\n2004 – 2010\n\n' + L + '\n\nSKILLS\n\n· Customer Service Excellence\n· Order Taking & Serving\n· POS System Operation\n· Table Setting & Maintenance\n· Communication & Teamwork\n\n' + L + '\n\nREFERENCES\n\nMr. Roberto Gomez\nRestaurant Manager\n09123456789\n\nMs. Linda Cruz\nShift Supervisor\n09234567890\n\nMr. Mario Diaz\nFood & Beverage Head\n09345678901';

    // BARISTA
    templates.barista = header + L + '\n\nPROFESSIONAL SUMMARY\n\nPassionate and skilled barista with experience in coffee preparation, customer service, and cafe operations.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: March 22, 1997\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nBarista\nCoffee Shop – Alabang\n\n· Prepared and served coffee beverages according to standards.\n· Operated espresso machines and coffee brewing equipment.\n· Provided excellent customer service and product recommendations.\n\nCafe Staff\nCafe – Muntinlupa City\n\n· Prepared food and beverage orders accurately.\n· Maintained cleanliness of cafe area and equipment.\n· Handled cash and digital payments.\n\nCoffee Attendant\nHotel Lobby Cafe – Tunasan\n\n· Served coffee and refreshments to hotel guests.\n· Managed inventory of coffee beans and supplies.\n· Ensured quality and consistency of beverages.\n\n' + L + '\n\nEDUCATION\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2011 – 2015\n\nMuntinlupa Elementary School (MES)\n2005 – 2011\n\n' + L + '\n\nSKILLS\n\n· Espresso Machine Operation\n· Coffee Brewing Techniques\n· Customer Service\n· Cash Handling\n· Time Management\n\n' + L + '\n\nREFERENCES\n\nMs. Grace Martinez\nCafe Manager\n09123456789\n\nMr. David Garcia\nOperations Head\n09234567890\n\nMs. Rachel Tan\nSenior Barista\n09345678901';

    // CAREGIVER
    templates.caregiver = header + L + '\n\nPROFESSIONAL SUMMARY\n\nCompassionate and patient caregiver with experience in providing care for elderly, children, and individuals with special needs.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: January 5, 1992\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nCaregiver\nElderly Care Facility – Muntinlupa City\n\n· Assisted residents with activities of daily living.\n· Monitored health conditions and reported changes to nursing staff.\n· Provided companionship and emotional support to residents.\n\nHome Caregiver\nPrivate Home – Alabang\n\n· Provided personalized care to an elderly client in home setting.\n· Assisted with medication reminders and meal preparation.\n· Maintained a clean and safe living environment.\n\nChild Caregiver\nFamily Residence – Tunasan\n\n· Cared for children including feeding, bathing, and playtime.\n· Assisted with homework and educational activities.\n· Ensured children\'s safety and well-being at all times.\n\n' + L + '\n\nEDUCATION\n\nCaregiving NC II Certificate\nTechnical Education and Skills Development Authority (TESDA)\n2018\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2006 – 2010\n\nMuntinlupa Elementary School (MES)\n2000 – 2006\n\n' + L + '\n\nSKILLS\n\n· Patient Care & Assistance\n· Daily Living Activities Support\n· Medication Reminders\n· Companionship & Emotional Support\n· Safety & Emergency Response\n\n' + L + '\n\nREFERENCES\n\nMs. Maria Santos\nCare Facility Manager\n09123456789\n\nMs. Ana Reyes\nNurse Supervisor\n09234567890\n\nMr. Jose Garcia\nClient Family Member\n09345678901';

    // RECEPTIONIST
    templates.receptionist = header + L + '\n\nPROFESSIONAL SUMMARY\n\nProfessional and friendly receptionist with experience in front desk operations, customer service, and administrative support.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Female\n· Nationality: Filipino\n· Date of Birth: May 10, 1996\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nReceptionist\nOffice Building – Alabang\n\n· Greeted visitors and directed them to appropriate offices.\n· Answered and transferred phone calls professionally.\n· Managed appointment scheduling and meeting room bookings.\n\nFront Desk Associate\nHotel – Muntinlupa City\n\n· Checked in and checked out guests efficiently.\n· Handled guest inquiries and complaints promptly.\n· Processed payments and maintained guest records.\n\nAdministrative Assistant\nCompany – Tunasan\n\n· Managed front desk operations and visitor logs.\n· Assisted with filing, data entry, and correspondence.\n· Ordered and maintained office supplies inventory.\n\n' + L + '\n\nEDUCATION\n\nBachelor of Science in Office Administration\nPamantasan ng Lungsod ng Muntinlupa\n2018\n\nMuntinlupa National High School (MNHS)\n2010 – 2014\n\nMuntinlupa Elementary School (MES)\n2004 – 2010\n\n' + L + '\n\nSKILLS\n\n· Customer Service & Communication\n· Phone Etiquette & Call Handling\n· Appointment Scheduling\n· Record Keeping & Data Entry\n· Multitasking & Organization\n\n' + L + '\n\nREFERENCES\n\nMs. Grace Martinez\nOffice Manager\n09123456789\n\nMr. David Garcia\nHR Supervisor\n09234567890\n\nMs. Rachel Tan\nOperations Head\n09345678901';

    // TECHNICIAN
    templates.technician = header + L + '\n\nPROFESSIONAL SUMMARY\n\nSkilled and detail-oriented technician with experience in equipment maintenance, repair, and troubleshooting.\n\n' + L + '\n\nPERSONAL PROFILE\n\n· Gender: Male\n· Nationality: Filipino\n· Date of Birth: September 15, 1991\n· Religion: Roman Catholic\n· Civil Status: Single\n· Language Spoken: English and Tagalog\n\n' + L + '\n\nWORK EXPERIENCES\n\nMaintenance Technician\nManufacturing Company – Muntinlupa City\n\n· Performed preventive maintenance on production equipment.\n· Diagnosed and repaired mechanical and electrical issues.\n· Maintained accurate maintenance logs and documentation.\n\nService Technician\nElectronics Company – Alabang\n\n· Installed, tested, and repaired electronic equipment.\n· Provided technical support to customers.\n· Documented service calls and repair reports.\n\nIT Technician\nOffice Building – Tunasan\n\n· Maintained computer systems and network infrastructure.\n· Troubleshot hardware and software issues.\n· Installed and configured software applications.\n\n' + L + '\n\nEDUCATION\n\nDiploma in Industrial Technology\nTechnical Education and Skills Development Authority (TESDA)\n2013\n\nHigh School Graduate\nMuntinlupa National High School (MNHS)\n2005 – 2009\n\nMuntinlupa Elementary School (MES)\n1999 – 2005\n\n' + L + '\n\nSKILLS\n\n· Equipment Maintenance & Repair\n· Troubleshooting & Diagnostics\n· Preventive Maintenance\n· Technical Documentation\n· Safety Compliance\n\n' + L + '\n\nREFERENCES\n\nEngr. Ramon Reyes\nMaintenance Manager\n09123456789\n\nEngr. Carlos Santos\nTechnical Head\n09234567890\n\nEngr. Eduardo Lopez\nSenior Technician\n09345678901';

    return templates[jobType] || null;
  }
};
